---
title: "Project Home"
site: workflowr::wflow_site
# output:
#   workflowr::wflow_html:
#     toc: false
output:
  bookdown::html_document2:
    toc: false
editor_options:
  chunk_output_type: console
  markdown: 
    wrap: 72
---

This is the website for the research project "VSA Altitude Hold".

If you have cloned the project to a local computer this website is
rendered in the `docs` subdirectory of the project directory.

If you are using `workflowr` to publish the research website it will
also be rendered online to GitHub Pages.

This page acts as a table of contents for the website. There are links
to the web pages generated from the analysis notebooks and to the
rendered versions of any manuscripts/documents/presentations.

------------------------------------------------------------------------

# Overview documents {.unnumbered}

## [Design Notes](design_notes.html) {.unnumbered}

This notebook is for keeping notes about potential approaches for
implementing altitude hold in VSA.

------------------------------------------------------------------------

# Publications {.unnumbered}

Links to rendered manuscripts and presentations will go here.

------------------------------------------------------------------------

# Empirical Notebooks {.unnumbered}

This project repository deals with the conceptual issues of using VSA
for altitude hold. Actual implementation occurs in the
[gym-copter](https://github.com/simondlevy/gym-copter) repository So the
empirical work in this repository is limited to exploration of
VSA-specific issues.

## Characterise Simulation Data {.unnumbered}

These notebooks characterise data generated by the simulation of the
classically implemented altitude hold controller. We need to understand
the properties of the signals in order to design VSA implementations of
them.

### [Single Target Simulations](characterise_single_target_data.html) {.unnumbered}

The set of simulation data files analysed in this notebook have a single
target altitude that is constant for the duration of each simulation.

### [Multiple Target Simulations](characterise_multiple_target_data.html) {.unnumbered}

The set of simulation data files analysed in this notebook have multiple
target altitudes within each simulation.

## [Simulation Framework](simulation_framework.html) {.unnumbered}

This notebook implements gives examples of running the software
framework for simulation of the PID altitude hold controller.

## [VSA Basic Operators](vsa_basic_operators.html) {.unnumbered}

This notebook implements and tests the basic VSA operators. The
reasoning behind the design choices id given in the [Design
Notes](design_notes.html) notebook.
